id: P008026
initial_creation_type: ocr
source_metadata:
  id: bdr:W27218
  title: གྲུབ་པའི་མཐའ་རྣམ་པར་བཤད་པའི་མཛོད
  author: ''
  volumes:
    56cac242266a4801be9c2b96a5170b00:
      image_group_id: I1CZ4689
      title: ''
      volume_number: 1
      total_pages: 256
ebook_metadata:
  title: གྲུབ་པའི་མཐའ་རྣམ་པར་བཤད་པའི་མཛོད
  author: ''
  sku: P008026
  cover: cover.jpg
  layers:
  - pagination
