id: opecha:P008026
initial_creation_type: ocr
source_metadata:
  id: bdr:W27218
  title: གྲུབ་པའི་མཐའ་རྣམ་པར་བཤད་པའི་མཛོད
  volume:
    faaadbc9c056485a94d40655eee8d15a:
      image_group_id: I1CZ4689
      title: Volume 1 of grub pa'i mtha' rnam par bshad pa'i mdzod
      volume_number: 1
      total_pages: 256
  author: ''
ebook_metadata:
  title: གྲུབ་པའི་མཐའ་རྣམ་པར་བཤད་པའི་མཛོད
  author: ''
  sku: P008026
  cover: cover.jpg
  layers:
  - pagination
