id: I5D84DF1F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:01:02+00:00'
last_modified: '2022-06-08T17:54:27.933853+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27218
  title: གྲུབ་པའི་མཐའ་རྣམ་པར་བཤད་པའི་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E1D0:
      image_group_id: I1CZ4689
      title: Volume 1 of grub pa'i mtha' rnam par bshad pa'i mdzod
      total_pages: 256
      order: 1
      base_file: E1D0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
